name: CI (TypeScript)

on:
  pull_request:
    paths:
      - '.github/workflows/ci-typescript.yml'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.json'
      - '**package.json'
      - '.eslint*'
      - '*prettier*'
      - '**babel.config.js'
      - 'tsconfig.json'
      - '**yarn.lock'
      - '**react-native.config.js'
      - '**metro.config.js'
      - '!*/android/**'
      - '!*/ios/**'

  push:
    branches: [development]
    paths:
      - '.github/workflows/ci-typescript.yml'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.json'
      - '**package.json'
      - '.eslint*'
      - '*prettier*'
      - '**babel.config.js'
      - 'tsconfig.json'
      - '**yarn.lock'
      - '**react-native.config.js'
      - '**metro.config.js'
      - '!*/android/**'
      - '!*/ios/**'

concurrency:
  group: ci-typescript-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-style-typescript:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node and npm registry
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'yarn'

      - name: Install node_modules
        run: yarn install --frozen-lockfile

      - name: Lint Typescript
        run: yarn lint

  test-build-typescript:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node and npm registry
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'yarn'

      - name: Install node_modules
        run: yarn install --frozen-lockfile

      - name: Install node_modules (example/)
        run: yarn install --frozen-lockfile --cwd example

      - name: Compile TypeScript
        run: yarn typescript
